{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "social.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "social.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ required "ingress.host is required" .Values.ingress.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.routes }}
          {{- $svc := index $.Values.services .service }}
          {{- if $svc.enabled }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .service }}-service
                port:
                  number: {{ $svc.port }}
          {{- end }}
          {{- end }}
{{- end }}
