{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "social.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: redis
{{- end }}
