{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "social.sa" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "social.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
automountServiceAccountToken: false
{{- end }}
