#!/usr/bin/env python3
"""Generate Compose's Kong config from the Helm source (requires Helm/PyYAML).
Use --env-file .env to share ALLOWED_ORIGINS with the application services.
"""
import argparse
from pathlib import Path
import subprocess
import tempfile
import yaml

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--env-file', type=Path)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
origins = 'http://localhost:3000,http://localhost:3001'
if args.env_file:
    for line in args.env_file.read_text().splitlines():
        if line.startswith('ALLOWED_ORIGINS='):
            origins = line.split('=', 1)[1].strip().strip('\"\'')
with tempfile.NamedTemporaryFile(mode='w', suffix='.yaml') as values:
    yaml.safe_dump({'config': {'ALLOWED_ORIGINS': origins}}, values)
    values.flush()
    rendered = subprocess.check_output([
        'helm', 'template', 'social-media', str(root / 'deployments/helm/social-media-backend'),
        '-f', values.name, '--show-only', 'templates/kong-configmap.yaml'], text=True)
config = '# Generated by scripts/render-kong-compose.py; edit Helm values/templates.\n' + yaml.safe_load(rendered)['data']['kong.yml']
output = root / 'docker/kong/kong.yml'
if args.check:
    if output.read_text() != config:
        raise SystemExit('Kong Compose configuration is stale; regenerate it.')
else:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(config)
print('Kong Compose configuration is current.')
